import Head from 'next/head';
import Typography from '@/components/common/Typography';
import Logo from '../components/common/Logo';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
