import Head from 'next/head';

import { styled } from '@root/stitches.config';
import { Bottom, LinedTitle, MainMovieThumbnail, ThumbnailCard } from '@/components';

const DUMMY_MOVIE = {
  title: 'Joker',
  description:
    'In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs.\n She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets.',
  date: '2021',
  rating: 4.5,
  genres: ['Drama', 'Comedy', 'Adventure'],
  image: '/thumbnail.png',
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainMovieThumbnail movie={DUMMY_MOVIE} />
      <Content>
        <LinedTitle title={'Trending Movies'} />
        <FeatureSection>
          <MovieCard src="/thumbnail.jpeg" movie={DUMMY_MOVIE} />
          <MovieCard src="/thumbnail.jpeg" movie={DUMMY_MOVIE} />
          <MovieCard src="/thumbnail.jpeg" movie={DUMMY_MOVIE} />
          <MovieCard src="/thumbnail.jpeg" movie={DUMMY_MOVIE} />
          <MovieCard src="/thumbnail.jpeg" movie={DUMMY_MOVIE} />
        </FeatureSection>
        <MovieSection>
          <LinedTitle title={'Romance Movies'} />
          <FeatureSection>
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />
          </FeatureSection>
        </MovieSection>
        <MovieSection>
          <LinedTitle title={'Action Movies'} />
          <FeatureSection>
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />
            <MovieCard src="/thumbnail.jpeg" size="large" movie={DUMMY_MOVIE} />s
          </FeatureSection>
        </MovieSection>
      </Content>
      <StyledBottom />
    </>
  );
}

const Content = styled('div', {
  paddingInline: 40,
  zIndex: 105,
  position: 'relative',
  top: '-256px',

  '@bp2': {
    paddingInline: 24,
  },
});

const FeatureSection = styled('div', {
  width: '100%',
  display: 'flex',
  gap: 56,
  marginTop: 40,
  overflow: 'scroll',
  '&::-webkit-scrollbar': {
    width: 0,
  },
  '&::-webkit-scrollbar-thumb': {
    height: 0,
  },
});

const MovieCard = styled(ThumbnailCard, {
  objectFit: 'cover',
});

const MovieSection = styled('div', {
  marginTop: 72,
});

const StyledBottom = styled(Bottom, {
  position: 'relative',
  top: -100,
});
