import Head from 'next/head';
import styled from '@emotion/styled';
import {
  Button,
  HStack,
  Input,
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
  useDisclosure,
} from '@chakra-ui/react';

import { Bottom, UserUtilModal } from '@/components';

export default function MyPage() {
  const {
    isOpen: isChangePWOpen,
    onOpen: onChangePWOpen,
    onClose: onChangePWClose,
  } = useDisclosure();

  return (
    <>
      <Head>
        <title>Create Next Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content>
        <Tabs>
          <TabList color="white">
            <Tab>내정보</Tab>
            <Tab>티켓 조회</Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <Stack>
                <HStack gap={16}>
                  <Text color="white">이름</Text>
                  <Text color="white">홍길동</Text>
                </HStack>
                <HStack gap={16}>
                  <Text color="white">아이디</Text>
                  <Text color="white">홍길동</Text>
                </HStack>

                <HStack gap={16}>
                  <Text color="white">핸드폰 번호</Text>
                  <Text color="white">홍길동</Text>
                </HStack>
                <HStack gap={16}>
                  <Text color="white">포인트</Text>
                  <Text color="white">홍길동</Text>
                </HStack>
                <Button color="blue" onClick={onChangePWOpen}>
                  비밀번호 변경
                </Button>
              </Stack>
            </TabPanel>
            <TabPanel>
              <Stack>
                <Text color="white">티켓 정보</Text>
              </Stack>
            </TabPanel>
          </TabPanels>
        </Tabs>
      </Content>
      <UserUtilModal type={'changePW'} isOpen={isChangePWOpen} onClose={onChangePWClose} />
      <Bottom />
    </>
  );
}

const Content = styled.div`
  padding-inline: 240px;
  background-color: #222;

  ${({ theme }) =>
    `@media (max-width: ${theme.bp.mobile}) {
      padding-inline: 24px;
    }`};
`;
